import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile
import compat.patrouille.Severity

buildscript {
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.kotlin.serializationPlugin
		classpath libs.dokkaPlugin
		classpath libs.gradleMavenPublishPlugin
		classpath libs.spotlessPlugin
		classpath libs.android.gradlePlugin
		classpath libs.buildConfigPlugin
		classpath libs.compatPlugin
	}
	repositories {
		mavenCentral()
		google()
	}
}

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'
apply plugin: 'com.diffplug.spotless'
apply plugin: 'com.android.lint'
apply plugin: 'com.github.gmazzo.buildconfig'
apply plugin: 'com.gradleup.compat.patrouille'

gradlePlugin {
	plugins {
		kmpMissingTargets {
			id = "com.jakewharton.kmp-missing-targets"
			displayName = "KMP Missing Targets"
			description = "Gradle plugin which identifies Kotlin multiplatform targets you should be supporting"
			implementationClass = "com.jakewharton.kmpmt.MissingTargetsPlugin"
		}
	}
}

tasks.named("validatePlugins") {
	enableStricterValidation = true
}

dependencies {
	compileOnly gradleApi()
	implementation libs.kotlin.gradlePlugin
	implementation libs.kotlinx.serialization

	testImplementation libs.junit
	testImplementation libs.assertk
	testImplementation libs.testParameterInjector
	testImplementation gradleTestKit()

	lintChecks libs.androidx.gradlePluginLints
}

kotlin {
	explicitApi()
}

// HEY! If you update the minimum-supported Gradle version check to see if the Kotlin language version or
// Java targets below can be bumped. See https://docs.gradle.org/current/userguide/compatibility.html.
def minimumGradleVersion = '9.0'
configurations.apiElements {
	attributes {
		attribute(
			GradlePluginApiVersion.GRADLE_PLUGIN_API_VERSION_ATTRIBUTE,
			objects.named(GradlePluginApiVersion, minimumGradleVersion),
		)
	}
}

compatPatrouille {
	java(17)
	kotlin('2.2.0')
	checkApiDependencies(Severity.ERROR)
	checkRuntimeDependencies(Severity.ERROR)
}

buildConfig {
	sourceSets.getByName('test') {
		useKotlinOutput {
			packageName = 'com.jakewharton.kmpmt'
			topLevelConstants = true
		}
		buildConfigField(String, 'MINIMUM_GRADLE_VERSION', minimumGradleVersion)
		buildConfigField(String, "KMPMT_VERSION", VERSION_NAME)
	}
}

tasks.withType(KotlinJvmCompile).configureEach {
	compilerOptions {
		jvmDefault = JvmDefaultMode.NO_COMPATIBILITY
	}
}

tasks.named("test") {
	dependsOn(':publishAllPublicationsToTestingRepository')
	inputs.dir('src/test/fixtures')

	testLogging {
		if (System.getenv("CI") == "true") {
			events = ["failed", "skipped", "passed"]
		}
		exceptionFormat "full"
	}

	// Required to test configuration cache in tests when using withDebug()
	// https://github.com/gradle/gradle/issues/22765#issuecomment-1339427241
	jvmArgs(
		"--add-opens",
		"java.base/java.util=ALL-UNNAMED",
		"--add-opens",
		"java.base/java.util.concurrent.atomic=ALL-UNNAMED",
		"--add-opens",
		"java.base/java.lang.invoke=ALL-UNNAMED",
		"--add-opens",
		"java.base/java.net=ALL-UNNAMED",
	)
}

publishing {
	repositories {
		maven {
			name = "testing"
			url = "${rootProject.projectDir}/build/localMaven"
		}
	}
}

spotless {
	kotlin {
		target('**/*.kt')
		ktfmt(libs.ktfmt.get().version).googleStyle()
	}
}
