[versions]
kotlin = "2.2.21"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:8.1.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"
buildConfigPlugin = "com.github.gmazzo.buildconfig:plugin:6.0.0"
compatPlugin = "com.gradleup.compat.patrouille:compat-patrouille-gradle-plugin:0.1.0"

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.19"
ktfmt = "com.facebook:ktfmt:0.59"

android-gradlePlugin = "com.android.tools.build:gradle:8.13.1"
androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"
